name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint -r requirements.txt
        
    - name: Analysing the code with pylint
      run: |
        # Set PYTHONPATH so pylint can resolve the app/ module folder correctly
        # and disable convention, refactor, and specific warning codes to focus on build errors.
        PYTHONPATH=. pylint app/ --disable=C,R,logging-fstring-interpolation,broad-exception-caught,broad-exception-raised,raise-missing-from,f-string-without-interpolation,unused-argument,unused-import,unused-variable,redefined-outer-name
